### ISSUE TITLE
Error when calling PartitionAndPlacePartitioner

### ISSUE THREAD

**Issue by gdikov** [SpiNNakerManchester/sPyNNaker7#16]
Hello everyone,

I wasn't quite sure if I should post the issue here or on the PACMAN repo instead and therefore sorry if I misplaced that one. 

#### Setup description
I have a workflow which creates a network of arbitrary size but with a fixed topology whose interconnected populations of neurons (targets) are also connected to SpikeSourceArray input populations (sources). The targets have been set to stream their output in real-time. 

#### Problem
The workflow fails during partitioning graph vertices with the following (abbreviated) error message:
>Partitioning graph vertices
|0%                          50%                         100%|
 2017-07-17 15:51:29 ERROR: Error when calling pacman.operations.partition_algorithms.partition_and_place_partitioner.PartitionAndPlacePartitioner.__call__ with inputs {'machine': [Machine: max_x=23, max_y=11, chips=[[Chip: x=0, y=0, sdram=117 MB, ip_address=192.168.2.1, router=[Router: clock_speed=157 MHz, emergency_routing=False,available_entries=1023, links=[[Link: source_x=0, source_y=0, source_link_id=0, destination_x=1, destination_y=0, default_from=3, default_to=3], [Link: source_x=0, source_y=0, source_link_id=1, destination_x=1, destination_y=1, default_from=4, default_to=4], [Link: source_x=0, source_y=0, source_link_id=2, destination_x=0, destination_y=1, default_from=5, default_to=5], [Link: source_x=0, source_y=0, source_link_id=3, destination_x=23, destination_y=0, default_from=0, default_to=0], [Link: source_x=0, source_y=0, source_link_id=4, destination_x=23, destination_y=11, default_from=1, default_to=1], [Link: source_x=0, source_y=0, source_link_id=5, destination_x=0, destination_y=11, default_from=2, default_to=2]]], processors=[[CPU: id=0, clock_speed=200 MHz, monitor=True], [.......] [CPU: id=17, clock_speed=200 MHz, monitor=False]], nearest_ethernet=16:8]]], 'graph': <pacman.model.graphs.application.application_graph.ApplicationGraph object at 0x7f79ee7c27a0>, 'preallocated_resources': <pacman.model.resources.pre_allocated_resource_container.PreAllocatedResourceContainer object at 0x7f79ec2af200>}

It is important to mention that the failing program runs successfully when using a sPyNNaker release from September 2016 instead of sPyNNaker7. 
I also tried to reproduce the error in a separate minimalistic script using a single source and target neurons but it ran just well. So it must be something in the network's topology that breaks it, I assume. However when I down-scaled my SNN such that only 32 populations are created (preserving the original topology) the PartitionAndPlacePartitioner completed without any exception. Then I tried it slightly larger (36 populations) and it failed with the aforementioned error message. 

Do you have any idea what might be causing that? A spynnaker.cfg issue? Or maybe I miss something when porting my sPyNNaker Sept 2016 code to sPyNNaker7? The only thing I have changed are some import statements:
 1) from `import spynnaker.pyNN` to `spynnaker7.pyNN`
 2) and also one broken old import: from `import spynnaker_external_devices_plugin.pyNN as external_device` to `from spynnaker_external_devices_plugin.pyNN import SpynnakerExternalDevicePluginManager` so that `SpynnakerExternalDevicePluginManager .activate_live_output_for(...)` can be applied on the targets.

Interestingly, the code ran without exceptions some two weeks ago but started to fail after I reinstalled the SpiNNaker tool chain on the 10.07.2017. I will try to revert to a previous commit and check whether it is any more successful. I will also try to compose a fairly small script reproducing this issue if you have absolutely no idea.

Thank you very much!

**Comment by alan-stokes** [comment]
HI gdikov. what size machine are you using? and what is the actual error message it produces? this is just the stack trace before the error message. 

how many atoms are in each population? it could be that you've just ran out of cores, in which case we would recommend running this on the HBP portal. 

regards
Alan

**Comment by gdikov** [comment]
Hi Alan,

Thank you for your quick reply! The architecture of the network allows for arbitrarily sized populations and the last time I tried it was 50 units in each. Now I tried with 1 neuron per population and it failed with the same error message. The machine I am using is also large enough to accommodate all 34 populations (it has 5135 cores -- 6 SpiNN5 boards).

I attach the entire relevant log and error message in the file below. 

[log.txt](https://github.com/SpiNNakerManchester/sPyNNaker7/files/1161791/log.txt)

Regards,
Georgi

**Comment by rowleya** [comment]
I believe this is fixed by SpiNNakerManchester/PACMAN#107

**Comment by gdikov** [comment]
@rowleya, indeed it is. Thank you!

**Comment by gdikov** [comment]
@rowleya I was too quick to report the success... While the error message disappeared for the very simple cases I tried some 2 hours ago (i.e. less <=33 populations and <=50 units within each) the workflow failed again, this time a bit later during the placing of graph vertices when I tried a slightly larger, i.e. >= 34 populations network. The number of units in population seems not to influence the outcome and I tried with both 1 and 100.  Again I attach the lengthy logs. 

[log.txt](https://github.com/SpiNNakerManchester/sPyNNaker7/files/1162309/log.txt)

**Comment by rowleya** [comment]
This error is less clear - can you attach the script (or a reduced version) that causes this issue?

**Comment by alan-stokes** [comment]
where are we at on this issue? we're currently trying to fix as many before the official release in October.

**Comment by gdikov** [comment]
Sorry, I didn't manage to reproduce the issue within a small script I tried some 10 days ago, and was subsequently involved in other stuff. I will give it another try tomorrow and come back to you asap.

**Comment by gdikov** [comment]
I pulled the newest spynnaker toolchain and compiled a short example which produces the same error as mentioned above. You can find attached the lengthy log message. 
Am I using the live spikes output wrongly or is it a PACMAN bug? 

```
import spynnaker7.pyNN as pyNN

from spynnaker7.pyNN.external_devices import SpynnakerLiveSpikesConnection, SpynnakerExternalDevicePluginManager


def create_targets(size=40, height=20):
    targets = []
    for i in range(size):
        target_pop = pyNN.Population(height, pyNN.IF_curr_exp, {'v_reset': -70.0},
                                     label="target_{0}".format(i))
        SpynnakerExternalDevicePluginManager.activate_live_output_for(target_pop,
                                                                      database_notify_host="localhost",
                                                                      database_notify_port_num=19996)
        targets.append(target_pop)
    return targets


def create_sources(size=40, height=20):
    sources = []
    for i in range(size):
        source = pyNN.Population(height, pyNN.SpikeSourceArray,
                                 {'spike_times': [[10]]}, label="source_{}".format(i))
        sources.append(source)
    return sources


pyNN.setup(timestep=0.2, min_delay=0.2, max_delay=2.0, threads=4)

sources = create_sources(size=20)
targets = create_targets(size=20)

for s, t in zip(sources, targets):
    pyNN.Projection(s, t, pyNN.OneToOneConnector(weights=10, delays=0.2))

labels = [t.label for t in targets]
live_connection = SpynnakerLiveSpikesConnection(receive_labels=labels, local_port=19996, send_labels=None)


def print_spikes(label, timestamp, neuron_ids):
    print(label, timestamp, neuron_ids)

for t in targets:
    live_connection.add_receive_callback(t.label, print_spikes)

pyNN.run(100)
pyNN.end()
```

It is also worth mentioning, that when the number of populations gets small enough (e.g. `size=16` in `create_sources()` and `create_targets()`) then an IndexError pops up:

```
[....]
Generating Router table report
|0%                          50%                         100%|
 ============================================================
2017-08-02 15:35:53 INFO: Time 0:00:00.000447 taken by unCompressedRoutingTableReports
Finding binaries
|0%                          50%                         100%|
 ============================================================
2017-08-02 15:35:53 INFO: Time 0:00:00.006938 taken by GraphBinaryGatherer
2017-08-02 15:35:53 INFO: Shutdown skipped as board is off for power save
Traceback (most recent call last):
  File "/home/gdikov/StereoVision/SemiframelessStereoMatching/failing_example.py", line 45, in <module>
    pyNN.run(100)
  File "/home/gdikov/spinn-dev-git_2017-08-02_13-10-07/dev/sPyNNaker7/spynnaker7/pyNN/__init__.py", line 156, in run
    globals_variables.get_simulator().run(run_time)
  File "/home/gdikov/spinn-dev-git_2017-08-02_13-10-07/dev/sPyNNaker/spynnaker/pyNN/abstract_spinnaker_common.py", line 307, in run
    AbstractSpinnakerBase._run(self, run_time)
  File "/home/gdikov/spinn-dev-git_2017-08-02_13-10-07/dev/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 851, in _run
    self._do_data_generation(steps[0])
  File "/home/gdikov/spinn-dev-git_2017-08-02_13-10-07/dev/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1524, in _do_data_generation
    inputs, algorithms, outputs, "data_generation")
  File "/home/gdikov/spinn-dev-git_2017-08-02_13-10-07/dev/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1039, in _run_algorithms
    executor.execute_mapping()
  File "/home/gdikov/spinn-dev-git_2017-08-02_13-10-07/dev/PACMAN/pacman/executor/pacman_algorithm_executor.py", line 433, in execute_mapping
    self._execute_mapping()
  File "/home/gdikov/spinn-dev-git_2017-08-02_13-10-07/dev/PACMAN/pacman/executor/pacman_algorithm_executor.py", line 439, in _execute_mapping
    do_injection(self._inputs)
  File "/home/gdikov/spinn-dev-git_2017-08-02_13-10-07/dev/PACMAN/pacman/executor/injection_decorator.py", line 227, in do_injection
    method(obj, object_to_inject)
  File "/home/gdikov/spinn-dev-git_2017-08-02_13-10-07/dev/PACMAN/pacman/executor/injection_decorator.py", line 42, in wrapper
    method(obj, arg)
  File "/home/gdikov/spinn-dev-git_2017-08-02_13-10-07/dev/PACMAN/pacman/executor/injection_decorator.py", line 119, in wrapper
    return wrapped_method(obj, *args, **new_args)
  File "/home/gdikov/spinn-dev-git_2017-08-02_13-10-07/dev/SpiNNFrontEndCommon/spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py", line 633, in update_buffer
    machine_time_step, first_machine_time_step, n_machine_time_steps)
  File "/home/gdikov/spinn-dev-git_2017-08-02_13-10-07/dev/SpiNNFrontEndCommon/spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py", line 365, in _fill_send_buffer
    for timeStamp in sorted(self._send_buffer_times[key]):
IndexError: list index out of range
```

Thanks and regards,
Georgi

[log.txt](https://github.com/SpiNNakerManchester/sPyNNaker7/files/1194023/log.txt)

**Comment by alan-stokes** [comment]
your error is to do with how to use the list of list format of sPyNNaker 0.75 (list of lists isn't officially supported by PyNN at this level).

So your error is on this line:
        source = pyNN.Population(height, pyNN.SpikeSourceArray,
                                 {'spike_times': [[10]]}, label="source_{}".format(i))

the array for spike times needs to be the size of your atoms. The reason it works with synfire chain example (that i assume you copied from) is because the SSA there is only 1 atom in size. Here you would need something akin to below to be correct.

[[10][][][][].....34 times......[]] to be valid. I would expect you to write the generation of this data as a for loop instead of manually. 

the other option is to use the PyNN way of [10] which means all neurons fire at time 10. 

hope this clears things up

regards
Alan

p.s. Glad i tested this, it found a error in master for running LPG's. This did not run to this point for the last 20 mins, and has 2 outstanding pull requests to get it to do so.

**Comment by alan-stokes** [comment]
just to finish, ill close this issue and you can open a new one if there's other issues. Because currently this is going past partition and place, which is what this issue was original covering.

**Comment by gdikov** [comment]
Thanks Alan, I missed that detail.
